# .github/workflows/api-test.yml
name: API Tests

on:
  pull_request:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Fetch only the latest commit to speed up the checkout process
          repository: ahdsab/FavaTesting
          token: ${{ secrets.TESTING_GITHUB_TOKEN }}  # Use the token to access the repo
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API tests
        working-directory: API_Testing
        run: |
          pytest -q
